In [1]:
from nba_api.stats.endpoints import leaguegamelog, boxscoretraditionalv3

In [2]:
game_log = leaguegamelog.LeagueGameLog(
    season="2025-26",
    season_type_all_star="Regular Season",
)

df = game_log.get_data_frames()[0]

In [3]:
df.head()

  SEASON_ID     TEAM_ID TEAM_ABBREVIATION  ...  PTS PLUS_MINUS VIDEO_AVAILABLE
0     22025  1610612744               GSW  ...  119         10               1
1     22025  1610612745               HOU  ...  124         -1               1
2     22025  1610612747               LAL  ...  109        -10               1
3     22025  1610612760               OKC  ...  125          1               1
4     22025  1610612737               ATL  ...  118        -20               1

[5 rows x 29 columns]

In [4]:
df[[
    "GAME_ID",
    "GAME_DATE",
    "TEAM_ABBREVIATION",
    "MATCHUP",
    "WL",
    "PTS",
    "PLUS_MINUS",
]].head(10)

      GAME_ID   GAME_DATE TEAM_ABBREVIATION      MATCHUP WL  PTS  PLUS_MINUS
0  0022500002  2025-10-21               GSW    GSW @ LAL  W  119          10
1  0022500001  2025-10-21               HOU    HOU @ OKC  L  124          -1
2  0022500002  2025-10-21               LAL  LAL vs. GSW  L  109         -10
3  0022500001  2025-10-21               OKC  OKC vs. HOU  W  125           1
4  0022500082  2025-10-22               ATL  ATL vs. TOR  L  118         -20
5  0022500083  2025-10-22               BOS  BOS vs. PHI  L  116          -1
6  0022500003  2025-10-22               CLE    CLE @ NYK  L  111          -8
7  0022500085  2025-10-22               NOP    NOP @ MEM  L  122          -6
8  0022500084  2025-10-22               CHI  CHI vs. DET  W  115           4
9  0022500004  2025-10-22               DAL  DAL vs. SAS  L   92         -33

In [5]:
game_id = df.iloc[0]["GAME_ID"]
game_id

'0022500002'

In [10]:
box = boxscoretraditionalv3.BoxScoreTraditionalV3(
    game_id=game_id
)
box_dfs = box.get_data_frames()
len(box_dfs)

3

In [11]:
player_df = box_dfs[0]

player_df.head()

       gameId      teamId     teamCity  ... foulsPersonal points plusMinusPoints
0  0022500002  1610612747  Los Angeles  ...             5     26           -14.0
1  0022500002  1610612747  Los Angeles  ...             2      9            -6.0
2  0022500002  1610612747  Los Angeles  ...             3     10            -4.0
3  0022500002  1610612747  Los Angeles  ...             3      3            -5.0
4  0022500002  1610612747  Los Angeles  ...             1     43            -8.0

[5 rows x 34 columns]

In [12]:
player_df.columns

Index(['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug',
       'personId', 'firstName', 'familyName', 'nameI', 'playerSlug',
       'position', 'comment', 'jerseyNum', 'minutes', 'fieldGoalsMade',
       'fieldGoalsAttempted', 'fieldGoalsPercentage', 'threePointersMade',
       'threePointersAttempted', 'threePointersPercentage', 'freeThrowsMade',
       'freeThrowsAttempted', 'freeThrowsPercentage', 'reboundsOffensive',
       'reboundsDefensive', 'reboundsTotal', 'assists', 'steals', 'blocks',
       'turnovers', 'foulsPersonal', 'points', 'plusMinusPoints'],
      dtype='str')

In [13]:
type(player_df)

pandas.DataFrame

In [14]:
player_df[
    [
        "teamTricode",
        "firstName",
        "familyName",
        "position",
        "minutes",
        "points",
        "reboundsTotal",
        "assists",
        "turnovers",
        "plusMinusPoints",
    ]
]

   teamTricode  firstName     familyName  ... assists turnovers  plusMinusPoints
0          LAL     Austin         Reaves  ...       9         5            -14.0
1          LAL        Rui      Hachimura  ...       3         1             -6.0
2          LAL    Deandre          Ayton  ...       0         4             -4.0
3          LAL       Gabe        Vincent  ...       1         0             -5.0
4          LAL       Luka         Dončić  ...       9         3             -8.0
5          LAL     Marcus          Smart  ...       0         3              2.0
6          LAL       Jake        LaRavia  ...       0         0             -5.0
7          LAL     Jaxson          Hayes  ...       1         1             -6.0
8          LAL     Jarred     Vanderbilt  ...       0         2             -4.0
9          LAL     Bronny          James  ...       0         0              0.0
10         LAL     Dalton         Knecht  ...       0         0              0.0
11         LAL  Christian         Koloko  ...       0         0              0.0
12         GSW      Jimmy     Butler III  ...       4         1             20.0
13         GSW   Jonathan        Kuminga  ...       6         2              4.0
14         GSW   Draymond          Green  ...       9         4             20.0
15         GSW    Brandin     Podziemski  ...       2         1             13.0
16         GSW    Stephen          Curry  ...       4         2              1.0
17         GSW      Buddy          Hield  ...       0         2              5.0
18         GSW       Gary      Payton II  ...       1         3              3.0
19         GSW         Al        Horford  ...       1         2            -10.0
20         GSW        Gui         Santos  ...       0         1              0.0
21         GSW       Will        Richard  ...       1         0            -11.0
22         GSW    Quinten           Post  ...       1         0              5.0
23         GSW     Trayce  Jackson-Davis  ...       0         0              0.0
24         GSW        Pat        Spencer  ...       0         0              0.0

[25 rows x 10 columns]

In [15]:
player_df[player_df["points"] > 10]

        gameId      teamId  ... points plusMinusPoints
0   0022500002  1610612747  ...     26           -14.0
4   0022500002  1610612747  ...     43            -8.0
12  0022500002  1610612744  ...     31            20.0
13  0022500002  1610612744  ...     17             4.0
16  0022500002  1610612744  ...     23             1.0
17  0022500002  1610612744  ...     17             5.0

[6 rows x 34 columns]