In [21]:
from nba_api.stats.endpoints import leaguegamelog, boxscoretraditionalv3, boxscoreadvancedv3
import pandas as pd
import time

In [22]:
game_log = leaguegamelog.LeagueGameLog(
    season="2025-26",
    season_type_all_star="Regular Season",
)

games_df = game_log.get_data_frames()[0]

In [23]:
game_ids = games_df["GAME_ID"].drop_duplicates().tolist()

In [24]:
len(game_ids)

1230

In [25]:
advanced_box = boxscoreadvancedv3.BoxScoreAdvancedV3(
    game_id=game_id
)

advanced_dfs = advanced_box.get_data_frames()
len(advanced_dfs)

2

In [35]:
advanced_player_df = advanced_dfs[0]

advanced_player_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,0022500082,1610612761,Toronto,Raptors,TOR,raptors,1627742,Brandon,Ingram,B. Ingram,...,20.0,0.438,0.462,0.293,0.293,119.71,119.71,99.76,67.0,0.085
1,0022500082,1610612761,Toronto,Raptors,TOR,raptors,1630567,Scottie,Barnes,S. Barnes,...,3.8,0.643,0.698,0.191,0.191,119.69,119.69,99.74,79.0,0.173
2,0022500082,1610612761,Toronto,Raptors,TOR,raptors,1627751,Jakob,Poeltl,J. Poeltl,...,16.7,0.875,0.829,0.161,0.161,120.18,120.18,100.15,56.0,0.089
3,0022500082,1610612761,Toronto,Raptors,TOR,raptors,1629628,RJ,Barrett,R. Barrett,...,17.4,0.833,0.880,0.212,0.212,118.53,118.53,98.78,73.0,0.178
4,0022500082,1610612761,Toronto,Raptors,TOR,raptors,1630193,Immanuel,Quickley,I. Quickley,...,12.5,0.417,0.472,0.205,0.205,117.07,117.07,97.56,70.0,0.085

In [36]:
advanced_player_df.columns

Index(['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug',
       'personId', 'firstName', 'familyName', 'nameI', 'playerSlug',
       'position', 'comment', 'jerseyNum', 'minutes',
       'estimatedOffensiveRating', 'offensiveRating',
       'estimatedDefensiveRating', 'defensiveRating', 'estimatedNetRating',
       'netRating', 'assistPercentage', 'assistToTurnover', 'assistRatio',
       'offensiveReboundPercentage', 'defensiveReboundPercentage',
       'reboundPercentage', 'turnoverRatio', 'effectiveFieldGoalPercentage',
       'trueShootingPercentage', 'usagePercentage', 'estimatedUsagePercentage',
       'estimatedPace', 'pace', 'pacePer40', 'possessions', 'PIE'],
      dtype='str')

In [26]:
test_game_ids = game_ids[:10]
test_game_ids

['0022500002',
 '0022500001',
 '0022500082',
 '0022500083',
 '0022500003',
 '0022500085',
 '0022500084',
 '0022500004',
 '0022500087',
 '0022500081']

In [27]:
player_game_dfs = []

for game_id in test_game_ids:
    box = boxscoretraditionalv3.BoxScoreTraditionalV3(
        game_id=game_id
    )

    player_df = box.get_data_frames()[0]

    player_game_dfs.append(player_df)

    time.sleep(0.6)

In [28]:
player_games_df = pd.concat(
    player_game_dfs,
    ignore_index=True
)

In [29]:
player_games_df.shape

(269, 34)

In [30]:
player_games_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1630559,Austin,Reaves,A. Reaves,...,1,4,5,9,2,0,5,5,26,-14.0
1,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629060,Rui,Hachimura,R. Hachimura,...,0,4,4,3,0,0,1,2,9,-6.0
2,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629028,Deandre,Ayton,D. Ayton,...,2,4,6,0,0,1,4,3,10,-4.0
3,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629216,Gabe,Vincent,G. Vincent,...,0,0,0,1,1,0,0,3,3,-5.0
4,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629029,Luka,Dončić,L. Dončić,...,0,12,12,9,2,1,3,1,43,-8.0

In [31]:
game_dates = (
    games_df[["GAME_ID", "GAME_DATE"]]
    .drop_duplicates()
    .rename(columns={"GAME_ID": "gameId", "GAME_DATE": "gameDate"})
)

In [32]:
player_games_df = player_games_df.merge(
    game_dates,
    on="gameId",
    how="left"
)

In [33]:
player_games_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints,gameDate
0,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1630559,Austin,Reaves,A. Reaves,...,4,5,9,2,0,5,5,26,-14.0,2025-10-21
1,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629060,Rui,Hachimura,R. Hachimura,...,4,4,3,0,0,1,2,9,-6.0,2025-10-21
2,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629028,Deandre,Ayton,D. Ayton,...,4,6,0,0,1,4,3,10,-4.0,2025-10-21
3,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629216,Gabe,Vincent,G. Vincent,...,0,0,1,1,0,0,3,3,-5.0,2025-10-21
4,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629029,Luka,Dončić,L. Dončić,...,12,12,9,2,1,3,1,43,-8.0,2025-10-21

In [34]:
player_games_df["gameDate"] = pd.to_datetime(
    player_games_df["gameDate"]
)

In [37]:
advanced_features = [
    "gameId",
    "personId",
    "teamId",
    "teamTricode",
    "minutes",

    # offense / efficiency
    "effectiveFieldGoalPercentage",
    "trueShootingPercentage",
    "usagePercentage",

    # playmaking
    "assistPercentage",
    "assistToTurnover",
    "assistRatio",
    "turnoverRatio",

    # rebounding
    "offensiveReboundPercentage",
    "defensiveReboundPercentage",
    "reboundPercentage",

    # impact / defense proxy
    "offensiveRating",
    "defensiveRating",
    "netRating",

    # context / workload
    "possessions",
    "PIE",
]

In [38]:
advanced_player_clean = advanced_player_df[advanced_features]

In [39]:
player_full_df = player_games_df.merge(
    advanced_player_clean,
    on=["gameId", "personId"],
    how="left",
    suffixes=("", "_advanced")
)

In [40]:
player_full_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,assistRatio,turnoverRatio,offensiveReboundPercentage,defensiveReboundPercentage,reboundPercentage,offensiveRating,defensiveRating,netRating,possessions,PIE
0,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1630559,Austin,Reaves,A. Reaves,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629060,Rui,Hachimura,R. Hachimura,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629028,Deandre,Ayton,D. Ayton,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629216,Gabe,Vincent,G. Vincent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0022500002,1610612747,Los Angeles,Lakers,LAL,lakers,1629029,Luka,Dončić,L. Dončić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN